name: my_flutter_app
description: "Tandoori Nights - Authentic Bangladeshi Restaurant App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # URL Launcher
  url_launcher: ^6.3.1
  
  # Firebase dependencies - LATEST VERSIONS
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  
  # Date formatting (REQUIRED for reservation_service.dart)
  intl: ^0.19.0
  
  # HTTP for API calls (Postcode lookup)
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/data/