name: my_flutter_app
description: "Tandoori Nights - Authentic Bangladeshi Restaurant App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # URL Launcher for phone calls and WhatsApp
  url_launcher: ^6.3.1
  
  # Firebase dependencies - LATEST VERSIONS (Updated)
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  
  # Date formatting (REQUIRED for reservation_service.dart and order tracking)
  intl: ^0.19.0
  
  # HTTP for API calls (Postcode lookup and address validation)
  http: ^1.2.2
  
  # REQUIRED: Crypto for guest order verification hashing
  crypto: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/data/
    - assets/images/mixed_kebab.jpg